/*
 * afl_harness.c — AFL++ harness that exercises foobar_target.c through FUSE.
 *
 * The fuzzer writes each test-case to the FUSE-mounted file (mnt/input), then
 * calls fuzz_foobar_from_path() which re-opens and reads the same path through
 * the FUSE VFS layer.  All I/O therefore flows through FUSE on every iteration.
 *
 * Compiled with afl-clang-fast  → persistent mode + SanCov edge coverage.
 * Compiled with plain gcc        → reads one test case from stdin (smoke test).
 */

#include <errno.h>
#include <fcntl.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#ifndef FUSE_INPUT_PATH
#define FUSE_INPUT_PATH "./mnt/input"
#endif

/* Defined in foobar_target.c, linked at compile time. */
void fuzz_foobar_from_path(const char *path);

/* ── AFL++ persistent-mode shims ─────────────────────────────────────────── */
/*
 * afl-clang-fast provides these macros via its runtime.  The fallbacks below
 * let the same source compile with plain gcc: a single iteration reading from
 * stdin, useful for verifying the FUSE wiring before AFL++ is involved.
 */
#ifndef __AFL_FUZZ_TESTCASE_LEN
static ssize_t       __afl_len;
static unsigned char __afl_buf[1 << 20];
#define __AFL_FUZZ_TESTCASE_LEN  __afl_len
#define __AFL_FUZZ_TESTCASE_BUF  __afl_buf
#define __AFL_FUZZ_INIT()        /* nothing */
#define __AFL_INIT()             /* nothing */
#define __AFL_LOOP(n)            ((__afl_len = read(STDIN_FILENO, __afl_buf, \
                                   sizeof(__afl_buf))) > 0)
#endif

__AFL_FUZZ_INIT();

/* ── write test-case bytes to the FUSE file ──────────────────────────────── */

static void write_to_fuse(const unsigned char *data, size_t len)
{
    int fd = open(FUSE_INPUT_PATH, O_WRONLY);
    if (fd < 0) {
        fprintf(stderr, "write_to_fuse open(%s): %s\n",
                FUSE_INPUT_PATH, strerror(errno));
        return;
    }
    /* Explicit ftruncate instead of O_TRUNC: FUSE3 doesn't always call the
     * truncate callback for O_TRUNC, leaving g_size stale.  ftruncate goes
     * through a separate code path that reliably resets g_size to 0 before
     * the write, preventing short inputs from inheriting bytes from longer
     * previous inputs (e.g. "foo" reading back as "foobar"). */
    if (ftruncate(fd, 0) < 0)
        fprintf(stderr, "write_to_fuse ftruncate: %s\n", strerror(errno));
    ssize_t w = write(fd, data, len);
    (void)w;
    close(fd);
}

/* ── entry point ─────────────────────────────────────────────────────────── */

int main(void)
{
    __AFL_INIT();

    unsigned char *buf = __AFL_FUZZ_TESTCASE_BUF;

    while (__AFL_LOOP(10000)) {
        size_t len = (size_t)__AFL_FUZZ_TESTCASE_LEN;
        if (len == 0)
            continue;

        /* 1. Push the fuzzer-generated bytes into the FUSE filesystem. */
        write_to_fuse(buf, len);

        /* 2. Target reads the same bytes back through FUSE and checks them. */
        fuzz_foobar_from_path(FUSE_INPUT_PATH);
    }

    return 0;
}
